name: Generate Product Report

permissions:
  contents: write

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: Fetch issues data
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh api graphql --paginate \
              -f owner="avenirs-esr" \
              -f repo="AVENIRS-Project" \
              -f query='
                query($owner: String!, $repo: String!, $endCursor: String) {
                  repository(owner: $owner, name: $repo) {
                    issues(
                      first: 100,
                      after: $endCursor,
                      orderBy: {
                        field: CREATED_AT,
                        direction: ASC
                      }
                    ) {
                      nodes {
                        number
                        title
                        url
                        state
                        issueType {
                          name
                        }
                        milestone {
                          title
                        }
                      }
                      pageInfo {
                        hasNextPage
                        endCursor
                      }
                    }
                  }
                }' \
            | jq -s '[.[].data.repository.issues.nodes[]]' > issues.json
  
      - name: Debug issues
        run: |
          echo "===== ISSUE COUNT ====="
          jq 'length' issues.json
    
          echo "===== ISSUE TYPES ====="
          jq -r '.[].issueType.name' issues.json | sort -u
    
          echo "===== MILESTONES ====="
          jq -r '.[] | select(.milestone != null) | .milestone.title' issues.json | sort -u

      - name: Debug counts
        run: |
          echo "Epics"
          jq '[.[] | select(.issueType != null and .issueType.name=="Epic")] | length' issues.json
      
          echo "User Stories"
          jq '[.[] | select(.issueType != null and .issueType.name=="User Story")] | length' issues.json
      
          echo "Bugs"
          jq '[.[] | select(.issueType != null and .issueType.name=="Bug")] | length' issues.json
    
      - name: Generate report
        run: |
          ##sed -i 's/\r$//' scripts/generate-report.sh
          chmod +x scripts/generate-report.sh
          ./scripts/generate-report.sh

      - name: Cleanup
        run: |
          rm -f issues.json
          rm -f milestones.txt
    
      - name: Commit report
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git status

          git diff scripts/generate-report.sh
    
          git add user-stories/
    
          git commit -m "Update report $(date +%F)" || echo "No changes"
    
          git pull --rebase origin main
    
          git push origin HEAD:main
  